version: '3.10'
# 두 개 띄우려고 이거 만듦
services:
  web:
    build: .  # Dockerfile 빌드
    command: python manage.py runserver 0.0.0.0:8000  # 장고 서버 실행 시키는 방법
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8000:8000
  db:
    image: nugoolmon/postgres # hamsm/capstonedb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  # 서비스 명
  pgadmin:
    # 사용할 이미지
    image: dpage/pgadmin4
    # 컨테이너 실행 시 재시작
    restart: always
    # 컨테이너명 설정
    container_name: pgadmin4
    # 접근 포트 설정 (컨테이너 외부:컨테이너 내부)
    ports:
      - "5050:80"
    # 환경 변수 설정
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: password
    # 볼륨 설정
    volumes:
      - ./data/pgadmin/:/var/lib/pgadmin